// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6DpmiDPOwUXn4-Ago3Uft6K6UuCFpQnU',
    appId: '1:713711466605:web:6a5c44c7e51ca9d89de764',
    messagingSenderId: '713711466605',
    projectId: 'nestify-b76e7',
    authDomain: 'nestify-b76e7.firebaseapp.com',
    storageBucket: 'nestify-b76e7.firebasestorage.app',
    measurementId: 'G-RKHQ8WQNQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPG4DNBoHEp1Az6V5BMBvsEPH3TeZ9RI0',
    appId: '1:713711466605:android:aec0b738ce04563e9de764',
    messagingSenderId: '713711466605',
    projectId: 'nestify-b76e7',
    storageBucket: 'nestify-b76e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYval9d0P8tgCZHpODs2bu8pStq3YLkjg',
    appId: '1:713711466605:ios:9818e567082f71079de764',
    messagingSenderId: '713711466605',
    projectId: 'nestify-b76e7',
    storageBucket: 'nestify-b76e7.firebasestorage.app',
    iosClientId: '713711466605-38r2pnlf0ueil59n0d9pv8vcdbi8sa4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.depiGraduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYval9d0P8tgCZHpODs2bu8pStq3YLkjg',
    appId: '1:713711466605:ios:9818e567082f71079de764',
    messagingSenderId: '713711466605',
    projectId: 'nestify-b76e7',
    storageBucket: 'nestify-b76e7.firebasestorage.app',
    iosClientId: '713711466605-38r2pnlf0ueil59n0d9pv8vcdbi8sa4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.depiGraduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6DpmiDPOwUXn4-Ago3Uft6K6UuCFpQnU',
    appId: '1:713711466605:web:08efe56f2d285ac69de764',
    messagingSenderId: '713711466605',
    projectId: 'nestify-b76e7',
    authDomain: 'nestify-b76e7.firebaseapp.com',
    storageBucket: 'nestify-b76e7.firebasestorage.app',
    measurementId: 'G-JXJV0QRRMV',
  );
}
